services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    volumes:
      - .:/var/www/html
      - portfolio_node_modules:/var/www/html/node_modules  # Use a named volume for node_modules
    ports:
      - "8000:8000"
      - "5173:5173"  # Vite server
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: portfolio-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - portfolio_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  portfolio_mysql_data:
  portfolio_node_modules:  # Add this volume